# Generated by Django 5.0.6 on 2026-06-18 19:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=255)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('content', models.TextField(blank=True, default='')),
                ('url', models.URLField(blank=True, default='', max_length=1000)),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('image_path', models.ImageField(blank=True, null=True, upload_to='alerts/%Y/%m/%d/')),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending Analysis'), ('processing', 'Processing'), ('analyzed', 'Analyzed'), ('failed', 'Analysis Failed')], default='pending', max_length=20)),
                ('is_threat', models.BooleanField(blank=True, null=True)),
                ('region', models.CharField(choices=[('judea_samaria', 'Judea & Samaria'), ('golan_heights', 'Golan Heights'), ('north', 'North'), ('south', 'South'), ('central', 'Central'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('threat_severity', models.PositiveSmallIntegerField(blank=True, help_text='1 (low) to 10 (critical).', null=True)),
                ('visual_summary', models.TextField(blank=True, default='', help_text='What the model spotted in the image, if any.')),
                ('analysis', models.JSONField(blank=True, default=dict, help_text='Full structured model response.')),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('judea_samaria', 'Judea & Samaria'), ('golan_heights', 'Golan Heights'), ('north', 'North'), ('south', 'South'), ('central', 'Central'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('day', models.DateField()),
                ('total_alerts', models.PositiveIntegerField(default=0)),
                ('threat_alerts', models.PositiveIntegerField(default=0)),
                ('avg_severity', models.FloatField(default=0.0)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-day', 'region'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('source_type', models.CharField(choices=[('telegram', 'Telegram Channel'), ('x', 'X (Twitter) Handle'), ('rss', 'RSS Feed'), ('gov', 'Government Site')], max_length=20)),
                ('identifier', models.CharField(help_text='Telegram channel/X handle/RSS URL/Gov URL used to fetch data.', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_external_id', models.CharField(blank=True, help_text='Last seen item id (e.g. Telegram message id) for de-duplication.', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='metric',
            constraint=models.UniqueConstraint(fields=('region', 'day'), name='uniq_region_day'),
        ),
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['source_type', 'is_active'], name='threats_sou_source__056df1_idx'),
        ),
        migrations.AddField(
            model_name='alert',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='threats.source'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['status'], name='threats_ale_status_fd859a_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['region', 'is_threat'], name='threats_ale_region_f7fd4d_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['-published_at'], name='threats_ale_publish_311ada_idx'),
        ),
        migrations.AddConstraint(
            model_name='alert',
            constraint=models.UniqueConstraint(fields=('source', 'external_id'), name='uniq_source_external_id'),
        ),
    ]
